name: Check the source code

on:
    pull_request:
        branches:
            - main
    push:
        branches: [main, dev, feature/*]

jobs:
    test:
        name: Check the source code
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'

            - name: Install packages
              run: yarn install --frozen-lockfile

            - name: Prettier
              run: yarn format

            - name: Lint
              run: yarn lint

            - name: test
              run: yarn coverage

